import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SupabaseProvider from '@/providers/SupabaseProvider'
import UserProvider from '@/providers/UserProvider'
import ModalProvider from '@/providers/ModalProvider'
import { ThemeProvider } from '@/providers/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider>
					<SupabaseProvider>
						<UserProvider>
							<ModalProvider />
							{children}
						</UserProvider>
					</SupabaseProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
